# Generated by Django 4.0.4 on 2022-05-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='team_away',
            new_name='team_away_id',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='team_home',
            new_name='team_home_id',
        ),
    ]
