# Generated by Django 4.0.4 on 2022-05-06 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0007_album_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('duration', models.TimeField(null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises_app.album')),
            ],
        ),
    ]
