# Generated by Django 4.0.4 on 2022-05-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0010_person_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
